version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.123
      POSTGRES_DB: db_gestion_estudiantil_usip
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_container
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin.123
      DB_NAME: db_gestion_estudiantil_usip
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  pgdata:
